
default: &default
  adapter: postgresql
  encoding: unicode
  username: libertbrice
  password:
  host: localhost
  pool: 5

development:
  <<: *default
  database: rails_event_loop_development

test:
  <<: *default
  database: rails_event_loop_test
